### ISSUE TITLE
dtype error when writing source summary

### ISSUE THREAD

**Issue by MaximMoinat** [thehyve/delphyne#164]
**Describe the bug**
```bash
etl_1         | Traceback (most recent call last):
etl_1         |   File "main.py", line 40, in <module>
etl_1         |     sys.exit(main(auto_envvar_prefix='ETL'))
etl_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
etl_1         |     return self.main(*args, **kwargs)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
etl_1         |     rv = self.invoke(ctx)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
etl_1         |     return ctx.invoke(self.callback, **ctx.params)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
etl_1         |     return callback(*args, **kwargs)
etl_1         |   File "main.py", line 36, in main
etl_1         |     etl.run()
etl_1         |   File "/app/src/main/python/wrapper.py", line 68, in run
etl_1         |     self.summarize()
etl_1         |   File "/usr/local/lib/python3.7/site-packages/delphyne/wrapper.py", line 171, in summarize
etl_1         |     etl_stats_logger.write_summary_files()
etl_1         |   File "/usr/local/lib/python3.7/site-packages/delphyne/model/etl_stats/etl_stats_reporter.py", line 108, in write_summary_files
etl_1         |     self.stats.sources_df.to_csv(output_dir / f'{time_str}_sources.tsv',
etl_1         |   File "/usr/local/lib/python3.7/site-packages/delphyne/model/etl_stats/etl_stats.py", line 158, in sources_df
etl_1         |     sources_df = pd.DataFrame(columns=EtlSource.df_column_order)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
etl_1         |     mgr = init_dict(data, index, columns, dtype=dtype)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
etl_1         |     val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
etl_1         |   File "/usr/local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1449, in construct_1d_arraylike_from_scalar
etl_1         |     dtype = dtype.dtype
etl_1         | AttributeError: type object 'object' has no attribute 'dtype'
```

**How to reproduce**
Only happens when running in docker and not when running locally. pandas version is the same (1.0.1)

**Expected behavior**
Source counts should be printed to log and file.

**Comment by Spayralbe** [comment]
Thanks for reporting this @MaximMoinat. It appears to occur for certain combinations of pandas and NumPy versions when creating an empty dataframe (https://github.com/pandas-dev/pandas/issues/39520).

Could you check if upgrading pandas to 1.0.5 solves the issue for you? If so, we could update the minimum required version.

**Comment by MaximMoinat** [comment]
Yes, that totally worked! Thanks!
